# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false
fortran: false
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

# added `matrix` and `addons` sections from `sodium/.travis.yml`, as travis log
# indicated that "Configuration failed because libsodium was not found."
matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: libsodium
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

# PPA is only needed for (legacy) Trusty. Can be removed when Trusty is EOL.
addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev
